In [9]:
import numpy as np

matA = np.array([[1,0,0],[-3,1,0],[0,0,1]])
matB = np.array([[1,2,1],[3,8,1],[0,4,1]])


# Matrix Multiplication

In [10]:
#The numpy easy way
print(np.dot(matA, matB))

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  4  1]]


In [15]:
#reinventing the wheel
def my_matrix_multiply(A, B):
    numRowA = len(A)
    numColA = len(A[0])
    numRowB = len(B)
    numColB = len(B[0])   
    
    #requirement for multiplication is the number of columns of A must match the number of rows of B
    if numColA != numRowB:
        print("Error multiplying: Columns of A do not equal rows of B")
        return
    
    #If A is m by n and B is n by p then C will be m by p. 
    #or, basically, the number of rows from A and the number of columns from B
    C = np.empty(shape=(numRowA, numColB))
    for i in range(numRowA):
        for j in range(numColB):
            for k in range(numColA):
                C[i][j] += A[i][k] * B[k][j]
    return C

print(my_matrix_multiply(matA, matB))

[[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  8.  2.]]
